### ISSUE TITLE
dealing with ambiguous input

### ISSUE THREAD

**Issue by dAnjou** [socksy/dictbot#2]
For example _band/Band_ exists in German and English. How do you want to deal with that? My idea would be to change the trigger command to something like:

```
!deen band
```

You could have `! band` for _de<->en_ as default. Mind the space after `!` though. It's important because without it _band_ would be used as a language pair for translating (_ba->nd_).

**Comment by socksy** [comment]
Problem with this is that it's bab.la choosing which way around it translates. I'll look into it though.

**Comment by dAnjou** [comment]
Nope, only when you ommit `ddict`. Otherwise you can control it. See the following 2 example, the first one uses _de->en_ and the second one uses _en->de_.

```
curl 'http://en.bab.la/widgets/dict.php' --data 'ddict=deen&search=mist'
```

``` html
<td class="lang1" style="vertical-align:top;color:#000000;font-size:11px;">
  <div style="width:94px;overflow:hidden;">
    <a class="result-link" href="http://en.bab.la/dictionary/german-english/mist" target="_blank">
      <strong>Mist</strong>
    </a>
    <span>{<abbr title="masculine">m</abbr>} [<abbr title="colloquial">coll.</abbr>]</span>
  </div>
</td>
<td class="lang2" style="vertical-align:top;color:#000000;font-size:11px;">
  <div style="width:94px;overflow:hidden;">
    <a class="result-link" href="http://en.bab.la/dictionary/english-german/crap" target="_blank">
      crap
    </a>
    <span> {<abbr title="noun">noun</abbr>} [<abbr title="colloquial">coll.</abbr>]</span>
  </div>
</td>
```

```
curl 'http://en.bab.la/widgets/dict.php' --data 'ddict=ende&search=mist'
```

``` html
<td class="lang1" style="vertical-align:top;color:#000000;font-size:11px;">
  <div style="width:94px;overflow:hidden;">
    <a class="result-link" href="http://en.bab.la/dictionary/english-german/mist" target="_blank">
      <strong>mist</strong>
    </a>
    <span>{<abbr title="noun">noun</abbr>} [<abbr title="meteorology">meteo.</abbr>]</span>
  </div>
</td>
<td class="lang2" style="vertical-align:top;color:#000000;font-size:11px;">
  <div style="width:94px;overflow:hidden;">
    <a class="result-link" href="http://en.bab.la/dictionary/german-english/nebel" target="_blank">
      Nebel
    </a>
    <span> {<abbr title="masculine">m</abbr>} [<abbr title="meteorology">meteo.</abbr>]</span>
  </div>
</td>
```

**Comment by socksy** [comment]
Does the !ende !deen commands sort this satisfactorily?

**Comment by dAnjou** [comment]
I thought it could be more dynamic. Example code: http://repl.it/0xC/1

**Comment by socksy** [comment]
That's some nice code, but I'm somewhat reticent.
1. Dictbot only lives in ##deutsch, which is only in English and German. Whilst it's nice to have the flexibility of other languages, it definitely seems overkill
2. It means the person has to write the entire string "ende" or "deen", instead of just specifying whether the current is in German or English with !en and !de
3. You're putting user input directly into the request. Whilst it doesn't appear to have any openings for vulnerabilities, it's possible that with a version of one of the libraries it would be possible to have some kind of injection issue here. It's just safer to never let that happen.
4. Assuming we only care about English and German, which we do, that functionality is already completely supported (as in `! defeated` works fine, as does `!ende defeated`)

As such, whilst I like the succinct nature of the regex to usage, I'm not sure I want to actually implement it that way.

**Comment by dAnjou** [comment]
1. There are people who speak Spanish, French, Russian, Finnish and other languages as well. And some of them are regulars.
2. Yes, but that's still okay, I think. Could maybe even prevent spamming with the bot.
3. I understand the concern and I'm aware of this of course. It was rather a proof of concept than production ready code.
4. See point 1.

I leave it up to you.

**Comment by socksy** [comment]
You made some valid points, so I've implemented it as you said, still leaving !en and !de as options, with things like "!frde bonjour" working. You can still do "! wort" but you can't do "!wort" anymore.
